### ISSUE TITLE
Support loading from nested jars

### ISSUE THREAD

**Issue by magneticflux-** [magneticflux-/ortools-java#10]
Blocked by https://github.com/magneticflux-/classpath-resource-extractor/issues/2

**Comment by magneticflux-** [comment]
@thedarkcder @riochr17 Could you test the changes in #11 locally using a Gradle Composite Build? Nested jar support requires an up-to-date version of at least Java 11. I found that `11.0.2` doesn't work, but `11.0.7` does work.

**Comment by langsweirdt** [comment]
Dear @magneticflux-,

I'm trying to use your package from a Spring/OSGI bundle. When invoking "OrToolsHelper.loadLibrary();", a java.nio.file.ProviderNotFoundException: Provider "bundle" not found is thrown. I assume this is relates to this issue?

Am I correct to say that a fix for this has been implemented at https://github.com/magneticflux-/classpath-resource-extractor/issues/2? If so, that issue mentions a requirement for Java 11, but my environment must support Java 8.

Any idea how I can proceed? (How) can I help you with testing?

Thanks.

**Comment by magneticflux-** [comment]
@langsweirdt I'm not well-versed in OSGi bundling, but I believe that message would result from a URI with the `bundle` scheme. That doesn't have a `java.nio.FileSystemProvider` by default, but it appears there was some discussion about supporting it here: https://mail.osgi.org/pipermail/osgi-dev/2017-May/006389.html.

I have not found a release of Java 8 that includes the ability to open a `ZipFileSystem` inside of a non-default `FileSystem`. This functionality is required for opening nested zip files, and likely required for opening `bundle:` URI locations as well. Recent Java 11 (LTS) releases fix this issue, which is why it is a requirement.
