### ISSUE TITLE
Error when deploy with spring & docker: java.nio.file.ProviderNotFoundException

### ISSUE THREAD

**Issue by loibui-futa** [magneticflux-/ortools-java#24]
@magneticflux- 

I've got an error when deploy an spring app on docker:

 `java.nio.file.ProviderNotFoundException: Provider not found at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:423) ~[na:na] at com.skaggsm.ClasspathUtils.visitUriRecursionHelper(ClasspathUtils.java:113) ~[classpath-resource-extractor-0.2.0.jar!/:na] at com.skaggsm.ClasspathUtils.visitUriRecursionHelper(ClasspathUtils.java:114) ~[classpath-resource-extractor-0.2.0.jar!/:na] at com.skaggsm.ClasspathUtils.visitUriAsPath(ClasspathUtils.java:87) ~[classpath-resource-extractor-0.2.0.jar!/:na] at com.skaggsm.ClasspathUtils.internalExtractResources(ClasspathUtils.java:53) ~[classpath-resource-extractor-0.2.0.jar!/:na] at com.skaggsm.ClasspathUtils.extractResources(ClasspathUtils.java:48) ~[classpath-resource-extractor-0.2.0.jar!/:na] at com.skaggsm.ClasspathUtils.extractResourcesToTempDirectory(ClasspathUtils.java:21) ~[classpath-resource-extractor-0.2.0.jar!/:na] at com.skaggsm.ortools.OrToolsHelper.extractLibrary(OrToolsHelper.java:65) ~[ortools-loader-8.0.8283.jar!/:na] at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.java:47) ~[ortools-loader-8.0.8283.jar!/:na] at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.java:57) ~[ortools-loader-8.0.8283.jar!/:na]`

Could you help me to figure out how to solve this issue?

The app was run successfully on gradle build and intellij idea.

Thank you very much

**Comment by loibui-futa** [comment]
The app was run successfully on gradle build and intellj idea.

**Comment by magneticflux-** [comment]
This might be similar to #13. How exactly are you packaging the Spring Boot application in a container?

**Comment by loibui-futa** [comment]
> This might be similar to #13. How exactly are you packaging the Spring Boot application in a container?

`FROM oracle-jdk:11.0.8 AS builder

RUN yum install -y wget unzip &&\
    yum clean all &&\
    rm -rf /var/cache/yum

ENV GRADLE_VERSION=6.6.1
RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip && \
	unzip gradle-${GRADLE_VERSION}-bin.zip && \
	rm -f gradle-${GRADLE_VERSION}-bin.zip

ENV PATH="/gradle-${GRADLE_VERSION}/bin:${PATH}"

WORKDIR /src
COPY . .
RUN gradle build -x test

FROM oracle-jdk:11.0.8

RUN yum install -y tzdata curl &&\
    yum clean all &&\
    rm -rf /var/cache/yum

WORKDIR /app
COPY --from=builder /src/build/libs/api-routing*.jar api-routing.jar

ENV SERVER_PORT=9000
EXPOSE 9000

CMD ["java", "-jar", "api-routing.jar"]
`

@magneticflux-  You can take a look at docker scripts above

**Comment by magneticflux-** [comment]
Hmm, now it looks like you might have run into #10. In particular, Oracle JDK builds lag behind OpenJDK builds slightly which might mean support for nested jar files hasn't landed in Oracle JDK 11.0.8. Can you try using Oracle JDK 11.0.10 or the latest OpenJDK build?
