### ISSUE TITLE
Bump ortools version to 7.6

### ISSUE THREAD

**Issue by lpicanco** [magneticflux-/ortools-java#7]
The current version of com.skaggsm.ortools is `7.5.7467` but the [latest](https://github.com/google/or-tools/releases/latest) version of ortools is `7.6.7691`.

An automated way to update these versions would be interesting.

**Comment by magneticflux-** [comment]
Thanks for letting me know, I'll make another issue for tracking automated releases in general.

I think I'll also include #3 in this next release.
